// Markdown card: short enough for a README section, a PR comment or a
// GitHub Actions job summary.

import { describeSuccessor } from "../successors.js";
import { fmt } from "./table.js";

export function renderMarkdown(result, { top = 5 } = {}) {
  const t = result.totals;
  const out = [];
  out.push(`## busfactor: ${t.packages} packages, ${relative(result.lockfile)}`);
  out.push("");

  if (!result.analysed) {
    out.push(`> ${result.ecosystem} is not yet analysed by busfactor v0 (names parsed only).`);
    pushSuccessors(out, result);
    return out.join("\n") + "\n";
  }

  out.push("| | |");
  out.push("|---|---:|");
  out.push(`| Dead (deprecated or archived) | **${t.dead}** |`);
  out.push(`| Dormant (>3y no release, >1y no commit) | **${t.dormant}** |`);
  out.push(`| Single publisher account | **${t.solo}** (${t.soloPercent}%) |`);
  out.push(`| With a security advisory | ${t.withAdvisories} |`);
  out.push(`| With a funding link | ${t.withFunding} |`);
  out.push(`| Distinct publisher accounts | ${t.humans} |`);
  out.push("");

  const humans = result.humans.filter((h) => h.solo > 0).slice(0, top);
  if (humans.length) {
    out.push("### Humans this project depends on most");
    out.push("");
    out.push("| Publisher | Alone | Total | Support |");
    out.push("|---|---:|---:|---|");
    for (const h of humans) {
      const login = h.orgOwned ? `${h.login} (org-owned?)` : h.login;
      const support = h.fundingLinks[0] ? `[sponsor](${h.fundingLinks[0]})` : "";
      out.push(`| ${login} | ${h.solo} | ${h.packages} | ${support} |`);
    }
    out.push("");
  }

  if (result.dead.length) {
    out.push("### Dead");
    out.push("");
    for (const p of result.dead.slice(0, top)) out.push(`- \`${p.name}\` - ${p.reason}`);
    if (result.dead.length > top) out.push(`- ... and ${result.dead.length - top} more`);
    out.push("");
  }

  if (result.dormant.length) {
    out.push("### Heaviest dormant");
    out.push("");
    for (const p of result.dormant.slice(0, top)) out.push(`- \`${p.name}\` - ${p.reason}, ${fmt(p.dependentRepos)} dependent repos`);
    if (result.dormant.length > top) out.push(`- ... and ${result.dormant.length - top} more`);
    out.push("");
  }

  pushSuccessors(out, result);
  out.push("");
  out.push(`<sub>Generated by [busfactor](https://github.com/GenAmed/busfactor) ${result.version} on ${result.scannedAt.slice(0, 10)}. Data: packages.ecosyste.ms. A publisher account is not always an active person.</sub>`);
  return out.join("\n") + "\n";
}

function pushSuccessors(out, result) {
  if (!result.successors.length) return;
  if (out[out.length - 1] !== "") out.push("");
  out.push("### Known successors");
  out.push("");
  for (const s of result.successors) {
    out.push(`- \`${s.package}\`: ${describeSuccessor(s)} ([source](${s.sources[0]}))`);
  }
}

function relative(file) {
  const cwd = process.cwd();
  return file.startsWith(cwd) ? file.slice(cwd.length + 1) : file;
}
